name: CI de la App
on: [push]

jobs:
  # Llamada al workflow centralizado
  CI-PR:
    uses: valentechy/GitHub-Actions-Gobernanza/.github/workflows/ci-pr-pipeline.yml@main
    with:
      target-env: 'production'
