name: CI de la App
on: [push]

jobs:
  # Llamada al workflow centralizado
  call-central-workflow:
    uses: valentechy/GitHub-Actions-Gobernanza/.github/workflows/ci-pipeline.yml@main
    with:
      target-env: 'production'
